1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that they are two procedure yields to same result
* What percent of the total variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [46]:

import numpy as np
from scipy import linalg as la
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

N = 1000
sigma2 = 3

x1 = np.random.randn(N)
x2 = x1+sigma2*np.random.randn(N)
x3 = 2*x1+x2

dtst = np.vstack((x1,x2,x3))


covmat=np.cov(dtst)
print("Covariance matrix:")
print(covmat)
e, V = la.eig(covmat)
print("\nEigenvalues of the covariance matrix:")
print(e)
print("\nEigenvectors of the covariance matrix:")
print(V)

U, S, Vt = la.svd(dtst)

print("\nEigenvalues of the covariance matrix SVD:")
print(S**2/(N-1))
print("\nEigenvectors of the covariance matrix SVD:")
print(U)

Covariance matrix:
[[ 1.01834239  0.9814426   3.01812737]
 [ 0.9814426   9.92714427 11.89002947]
 [ 3.01812737 11.89002947 17.92628422]]

Eigenvalues of the covariance matrix:
[ 2.68261548e+01+0.j -1.39677753e-16+0.j  2.04561607e+00+0.j]

Eigenvectors of the covariance matrix:
[[-0.11652471 -0.81649658  0.56546912]
 [-0.57603069 -0.40824829 -0.70818216]
 [-0.80908012  0.40824829  0.42275608]]

Eigenvalues of the covariance matrix SVD:
[2.68722660e+01 2.04582376e+00 1.22269925e-31]

Eigenvectors of the covariance matrix SVD:
[[-0.11645416  0.56548365 -0.81649658]
 [-0.57611905 -0.70811029 -0.40824829]
 [-0.80902736  0.42285702  0.40824829]]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset